// ======= DO NOT EDIT THIS FILE ============
import java.io.*;
class Main {
   public static void main(String args[]) throws Exception {      
       BufferedReader in = new BufferedReader(new InputStreamReader(System.in));
       System.out.print("Enter flight no: ");
       String flightNo = in.readLine();
       System.out.print("Enter flight route: ");
       String route = in.readLine();
       System.out.print("Enter flight fare: ");
       double fare = Double.parseDouble(in.readLine()); 
       System.out.printf("1. TC = 1 - test toString function\n2. TC = 2 - test getSaleFare function"
               + "\n3. TC = 3 - test getRoute function\n");       
       System.out.print("Enter TC: ");
       int tc = Integer.parseInt(in.readLine());
       System.out.println("OUTPUT:");      
       if(tc == 1) {
            Flight m = new Flight(route, fare);
            System.out.println(m);
            m = new VNFlight(route, flightNo, fare);
            System.out.println(m);
       }
       else if(tc == 2) {
           VNFlight b = new VNFlight(route, flightNo, fare);
           System.out.println(b.getSaleFare());
       }else if(tc == 3) {
           Flight b = new Flight(route, fare);
           System.out.println(b.getRoute());
       }
   }
 }
